### ISSUE TITLE
Will you release?

### ISSUE THREAD

**Issue by Shaxzy** [maikel233/X-HOOK-For-TF2#1]
Hello sir,
I'm just wondering if you will upload this? I like the cheat and I would like source code to make it undetected so I can use it on my main account.
Thanks in advance,
-Shaxzy

**Comment by maikel233** [comment]
Probably later.

**Comment by Shaxzy** [comment]
> Yeah i'm going to release it but i'm doing that later.

Alright, thanks man! I will wait 👍
